"""Called by generate_mosqito_zwst_field_crosscheck.jl -- not directly.

Reads {name, spl} cases (28 one-third-octave band levels, dB re 20 uPa,
25 Hz .. 12.5 kHz) from JSON (argv[1]) and, for BOTH `field_type="free"`
and `"diffuse"`, runs MoSQITo's stationary (ISO 532-1:2017 clause 5,
"Method 1") private stages @ d990c33f94f1 (Apache-2.0):
`_main_loudness(spec_third, field_type)` (core loudness, 21 x 1) then
`_calc_slopes(nm)` (spreading; total N in sone and 240-bin N'(z)).
Writes a Julia fixtures file (argv[2]).

Purpose: the only other Method 1 oracle in this repository
(test/fixtures/test_signal_1_nspec.csv) is free-field, so the diffuse
branch of `compute_excitation_levels` was previously checked only for
"differs from free". These cases pin it numerically. Inputs are synthetic
band-level vectors, not ISO material.
"""
import json
import sys

import numpy as np
from mosqito.sq_metrics.loudness.loudness_zwst._calc_slopes import _calc_slopes
from mosqito.sq_metrics.loudness.loudness_zwst._main_loudness import _main_loudness


def jl_vec(v):
    return "[" + ", ".join(repr(float(x)) for x in np.asarray(v).ravel()) + "]"


cases = json.load(open(sys.argv[1]))
out_path = sys.argv[2]

entries = []
for c in cases:
    spl = np.array(c["spl"], dtype=np.float64)
    assert spl.shape == (28,), c["name"]
    fields = []
    for ft in ("free", "diffuse"):
        nm = _main_loudness(spl, ft)
        N, N_specific = _calc_slopes(nm)
        N = float(np.squeeze(N))
        assert np.shape(N_specific) == (240,), (c["name"], ft, np.shape(N_specific))
        fields.append(
            f"""        {ft} = (
            N = {N!r},
            N_specific = {jl_vec(N_specific)},
        ),"""
        )
    entries.append(
        f"""    (
        name = "{c['name']}",
        spl = {jl_vec(spl)},
{chr(10).join(fields)}
    ),"""
    )

header = """# AUTOGENERATED by scripts/generate_mosqito_zwst_field_crosscheck.jl -- do not edit.
# Stationary (ISO 532-1:2017 clause 5, "Method 1") free- vs diffuse-field
# oracle: for each synthetic 28-band SPL vector, MoSQITo @ d990c33f94f1
# (Apache-2.0) `_main_loudness` + `_calc_slopes` total loudness N [sone]
# and 240-bin specific loudness N'(z) [sone/Bark], for BOTH field types.
# Not derived from any ISO-copyrighted material.
const ZWST_FIELD_FIXTURE_CASES = [
"""
with open(out_path, "w") as f:
    f.write(header + "\n".join(entries) + "\n]\n")
print(f"wrote {out_path}: {len(cases)} cases x 2 field types")
