"""Called by test/test_method2_annexb_conformance.jl -- not directly, and NOT
part of the committed fixture pipeline (contrast crosscheck_zwtv.py, which
IS the fixture generator).

Regenerates ONLY the 28 x nblocks `band_levels` matrix (the kernel's own
input contract, see src/method2.jl's module docstring) for an ISO 532-1
Annex B time-varying .wav file, via MoSQITo's private `_third_octave_levels`
@ d990c33f94f1 (Apache-2.0), and writes it as a Julia literal to a file path
supplied by the caller -- always a path OUTSIDE this repository (under
`tempname()`), never committed. This mirrors the licensing posture recorded
in .superpowers/sdd/zwtv-pins.md and test/fixtures/NOTICE.md: the Annex B
.wav itself, and any band-level/specific-loudness matrix derived from it,
retain enough structure to functionally reconstruct the ISO-copyrighted
recording, so they are regenerated fresh, locally, on demand, and discarded
by the calling test -- never vendored in test/fixtures/.

Same load/calibration convention as scripts/crosscheck_zwtv.py's Annex B
branch (transcribed from MoSQITo's own Annex B validation driver,
validations/sq_metrics/loudness_zwtv/validation_loudness_zwtv.py:191).

Usage: uv run --with mosqito --with numpy --with matplotlib python \\
    dump_annexb_band_levels.py <wav_path> <out_jl_path>
"""
import sys

import numpy as np
from mosqito.sq_metrics.loudness.loudness_zwtv._third_octave_levels import (
    _third_octave_levels,
)
from mosqito.utils import load as mosqito_load

wav_path, out_path = sys.argv[1], sys.argv[2]

sig, fs = mosqito_load(wav_path, wav_calib=2 * 2 ** 0.5)
band_levels, _band_time_axis, _freq = _third_octave_levels(sig, float(fs))
band_levels = np.asarray(band_levels, dtype=np.float64)


def jl_mat(m):
    rows = ["  " + " ".join(repr(float(x)) for x in row) for row in np.asarray(m)]
    return "[\n" + ";\n".join(rows) + "\n]"


with open(out_path, "w") as f:
    f.write(
        "# AUTOGENERATED (transient) by scripts/dump_annexb_band_levels.py -- "
        "never committed.\n"
        "# 28 x nblocks one-third-octave band levels [dB SPL], regenerated "
        "locally from an\n"
        f"# ISO 532-1 Annex B .wav ({wav_path}) via MoSQITo's private "
        "_third_octave_levels\n"
        "# @ d990c33f94f1 (Apache-2.0). See "
        "test/test_method2_annexb_conformance.jl.\n"
    )
    f.write(f"const ANNEXB_LOCAL_BAND_LEVELS = {jl_mat(band_levels)}\n")

print(f"wrote {out_path}: band_levels shape {band_levels.shape}")
